dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
  - oraclejdk8
env:
    - MONGODB_VER=mongodb-linux-x86_64-2.6.12 ANT_TEST=test               WIRED_TIGER=false
    - MONGODB_VER=mongodb-linux-x86_64-3.0.14 ANT_TEST=test_mongo_storage WIRED_TIGER=false
    - MONGODB_VER=mongodb-linux-x86_64-3.0.14 ANT_TEST=test_mongo_storage WIRED_TIGER=true
    - MONGODB_VER=mongodb-linux-x86_64-3.2.12 ANT_TEST=test_mongo_storage WIRED_TIGER=false
    - MONGODB_VER=mongodb-linux-x86_64-3.2.12 ANT_TEST=test_mongo_storage WIRED_TIGER=true
    - MONGODB_VER=mongodb-linux-x86_64-3.4.2  ANT_TEST=test_mongo_storage WIRED_TIGER=false
    - MONGODB_VER=mongodb-linux-x86_64-3.4.2  ANT_TEST=test_mongo_storage WIRED_TIGER=true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ant-optional

install:
  - cd ..
  - git clone https://github.com/kbase/jars
  - export JARSDIR=`pwd`/jars/lib/jars/
  - cd -

script:
  - cd ..
  - wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
  - tar xfz $MONGODB_VER.tgz
  - export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
  - cd -
  - cp -n test.cfg.example test.cfg
  - sed -i "s#^test.temp.dir=.*#test.temp.dir=temp_test_dir#" test.cfg
  - sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
  - sed -i "s#^test.mongo.wired_tiger.*#test.mongo.wired_tiger=$WIRED_TIGER#" test.cfg
  - sed -i "s#^test.jars.dir=.*#test.jars.dir=$JARSDIR#" test.cfg
  - cat test.cfg
  - ant $ANT_TEST

jobs:
  include:
    - stage: deploy
      env: # The following are secure declarations for DOCKER_USER, DOCKER_PASS
        - secure: "TuPVXnPhNpTo1nQVBWpS08PaKQT3lu3+EysH1RUAHEsy+zciJWqNsyq3Afun+63I0cA7RcUTzbZr7A/nIvqN7iWh8Y9tDdHOoDXfu1kFiDraoom1TJe7s0QOUKA/crg8IYW+BA+rjJiitsJDLu+wQ8/SFWbwIghsn9+pgajj+t/4QJ3jO2v5ZuJy/gExiqeWnrAtnbQDp/ZHxZxt7iZdw41s27eYUHJc8lUGdoY5487zmIJWl8WXwx9v1PDx0sa9RSL9TIjiKm90vPzxZZZ5uXquCIVeaI7GtNmwiebJllGKtqHbaUcVRXjrWFUR3PPGihPxkceunEpIipV3ERekfeQt0WWDl1W2qGDWSwxzcQWFtF32uJjBpZ31BtGw9lffranUmvpT5cFPfNkzgz0YMQx7S/aL9JjBeNyj5BoWNUdELeL3hc1ndjOeObQ8hiQXXpfOHGvRyCFXMKuC+fwvi8QfeePq3bya/zq85a57yU7KZsPPAGky+7/WD/wPCANmD+AZkxvzopOPufj6CrSUIw2+zpIz58o4YzcUjimhAerNQ098Fs3dm8mra643PaAkdQD8rL1m3ai6RtOxCMYAsiWbhtEJr713QHeDN+VHJeKOtbg0dgJjRwgBGilrhAZkdgy4fq1/cGwyG6tIsQgAKvb14UHQdB+qC9Qopk3k+gQ="
        - secure: "blqo6j7LlDRwxqs3mnSfFNX3o8Eex9uEiG+I/OJgcKPRLAJKSoNYTkywxoTJMBEn8t+fLZoCCbMWUBlOfc2orHgV1q/3cCjN3ofu6XNDAfxnFTb5F2qVxCGmksfVD9Cvp1IZsLTzj+TfFTvoBy9IP3IBdRT3jD1vX+Ae4PbRC1K5tewDwu/hRR3k5fcMSApHHHVz654So4Mvd9hZ35XAD+otGxc0CvUYkb5RCgZIfpS+F5fcmku488XDVV/wHfvjsJg3IVBMylCF2XED5LeI3kRkoIjwscVGQ8rnY5qauFms1Zsp+yxfmL6/aXddj/q0zcnLYB7Zu7hIKuTwWK4li4R7UY6ci0ze7aWQE+fYdPvSadbSRH5+Bh4lwcNbPrgK2GY7SyOf6idvYDluaJBm+7hBWEtl6w/DUX3rF1FMcRI4SEQYdddwe3Uf416BegVe/oihI+f9diFykh3oN+S3k05JxVXr/wYk9NQjPzQ1f6jsiG0cFf1r7ZpegsNKIUCaoetNqN8rcNUedAWoE5VLoIF9TKSjvyl0U8xOW3afccWtfCIr1LdO9IFLYHnfbljY5pXBViJWbJwJcfR7wgQBIlWQLhPtB6/0pSXlCMmpCOvb/8vhHqJd+goD7jhbLaJ7mIUdBrEcJra2rCmg+gDdQv3lj8ub4dXGhoj6PXs3xTU="
      script: # Only push to dockerhub if this isn't a PR and we're updating master or develop
        - docker pull kbase/kb_jre
        - ant docker_image
        - IMAGE_NAME=kbase/groups build/push2dockerhub.sh
after_success:
  - ls test-reports
  - bash <(curl -s https://codecov.io/bash) -f test-reports/coverage-report.xml

